CREATE TABLE users (
   id BIGSERIAL PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   age INTEGER CHECK (age >= 0 AND age <= 150),
   address TEXT,
   email VARCHAR(255) UNIQUE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);