version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: rag_postgres
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ragpass
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: rag_qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC
    volumes:
      - ./.qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama
    container_name: rag_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.ollama:/root/.ollama
    command: ["serve"]

